-- 코드를 입력하세요
# SELECT (CASE WHEN DATE_FORMAT(DATETIME, '%H') < 10 
#         THEN SUBSTR(DATE_FORMAT(DATETIME, '%H'), 1)
#        ELSE DATE_FORMAT(DATETIME, '%H')) AS HOUR, COUNT(*) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY DATE_FORMAT(DATETIME, '%H')
# ORDER BY 1

SELECT 
    HOUR(DATETIME) AS HOUR, 
    COUNT(*) AS COUNT
FROM (SELECT *
     FROM ANIMAL_OUTS
     WHERE HOUR(DATETIME) >= 9 AND HOUR(DATETIME) < 20) AS T
GROUP BY HOUR(DATETIME)
ORDER BY 1
