-- 코드를 입력하세요
# SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
# FROM FIRST_HALF
# GROUP BY FLAVOR
# ORDER BY 3 DESC, 1 ASC

SELECT FLAVOR
FROM (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    ORDER BY 3 DESC, 1 ASC) AS T